# cloudbuild.yaml — Secure version using Secret Manager for env vars

steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'

  # Step 2: Fetch secrets and build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔐 Loading secrets from Secret Manager..."
        export VITE_CHAT_URL=$(gcloud secrets versions access latest --secret=VITE_CHAT_URL)
        export VITE_SIGN_URL=$(gcloud secrets versions access latest --secret=VITE_SIGN_URL)
        export VITE_FIREBASE_API_KEY=$(gcloud secrets versions access latest --secret=VITE_FIREBASE_API_KEY)
        export VITE_FIREBASE_AUTH_DOMAIN=$(gcloud secrets versions access latest --secret=VITE_FIREBASE_AUTH_DOMAIN)
        export VITE_FIREBASE_PROJECT_ID=$(gcloud secrets versions access latest --secret=VITE_FIREBASE_PROJECT_ID)
        export VITE_FIREBASE_STORAGE_BUCKET=$(gcloud secrets versions access latest --secret=VITE_FIREBASE_STORAGE_BUCKET)
        export VITE_FIREBASE_MESSAGING_SENDER_ID=$(gcloud secrets versions access latest --secret=VITE_FIREBASE_MESSAGING_SENDER_ID)
        export VITE_FIREBASE_APP_ID=$(gcloud secrets versions access latest --secret=VITE_FIREBASE_APP_ID)
        export VITE_FIREBASE_MEASUREMENT_ID=$(gcloud secrets versions access latest --secret=VITE_FIREBASE_MEASUREMENT_ID)

        echo "🏗️ Building production app..."
        cd frontend
        npm run build

        echo "🚀 Deploying to Firebase Hosting..."
        npm install -g firebase-tools
        firebase experiments:enable webframeworks
        firebase deploy --only hosting --project ai-data-analyser --non-interactive
    dir: '.'

# Optional: log only to Cloud Logging (quiet output)
options:
  logging: CLOUD_LOGGING_ONLY
