# cloudbuild.yaml (Final Version with Web Frameworks Experiment Enabled)
steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'

  # Step 2: Build the production application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'

  # Step 3: Enable the webframeworks experiment and Deploy to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'npm install -g firebase-tools && firebase experiments:enable webframeworks && firebase deploy --only hosting --project ai-data-analyser --non-interactive'
    dir: 'frontend'

# Global options for the build
options:
  logging: CLOUD_LOGGING_ONLY