# cloudbuild.yaml (Corrected Version 2)
steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the production application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Step 3: Deploy to Firebase Hosting
  # Use the same node:20 image, which has npm,
  # and install firebase-tools before deploying.
  - name: 'node:20'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'npm install -g firebase-tools && firebase deploy --only hosting --project ai-data-analyser --non-interactive'

# Set the working directory for all steps to 'frontend'
options:
  
  logging: CLOUD_LOGGING_ONLY