# cloudbuild.yaml (Corrected Version)
steps:
  # 1. Install dependencies using the official Node.js 20 image
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'frontend'

  # 2. Build the production application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'frontend'

  # 3. Deploy to Firebase Hosting
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'npm install -g firebase-tools && firebase deploy --only hosting --project ai-data-analyser --non-interactive'
    dir: 'frontend'

options:
  logging: CLOUD_LOGGING_ONLY